### PR TITLE
Feature/profile page

### PR DESCRIPTION
**Pull request by ashleyspronk**

### CODE REVIEW

**Review by joohayoo — APPROVED** [review]
This looks amazing. It works great!

**Review by AlishaJS — CHANGES_REQUESTED** [review]
A few thoughts on UI (sorry if I said something different last night)
I'm thinking maybe just two toggles for each notification option (no toggle for just notifications). Seems like a user would look at it and wonder what notifications they would need, and having the extra step doesn't seem as necessary

"Record Transaction Reminders" could become "Receive reminders to enter transactions"
"Budget Exceeded Warning" could become "Receive notifications when budget is exceeded"

**Review by Alina086 — APPROVED** [review]
Looks great! Good work

**Comment by ashleyspronk** [comment]
@AlishaJS I'm going to merge this for now...just so that we can for sure have something in for tomorrow. It seems right now that there needs to be more discussion as a team about what we want it to look like so I'm going to wait to change anything until we can have that discussion

**Pull request merged**
