### PR TITLE
Redesign-reports

### PR DESCRIPTION
**Pull request by joohayoo**
Organized chart, drop-down categ labels, instead of percentages, for now, the labels are in most-least expense list, total sum under each categ shown

### CODE REVIEW

**Review by Alina086 — CHANGES_REQUESTED** [review]
I think the "before" and "after" toggle icons should be exchanged. The total for the first category seemed off. And for one of the categories' transactions, the amount seemed to be cut off.

**Comment by ashleyspronk** [comment]
I agree that the arrows should be switched. They should be facing towards the right when they are collapsed and turn downward when you expand a specific category. I also wonder if there's a way you could make it scroll down automatically when you expand a category.

**Comment by ashleyspronk** [comment]
I like the toggle switch. I also keep getting this error message...
Screenshot 2024-11-21 at 6 52 23 PM

**Comment by joohayoo** [comment]
yeah... that comment we've been having ever since handlepresscateg was implemented, need to take a look at it deeply

**Pull request merged**
